plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.discord4j:discord4j-core:3.3.0"
    implementation 'io.projectreactor:reactor-core:3.8.0'
    implementation 'io.lettuce:lettuce-core:7.0.0.RELEASE'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }

    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.25.2'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'ibutler.iButler' // Fully qualified main class
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

// Configure Spring Boot fat JAR
bootJar {
    enabled = true                     // ensure bootJar is active
    archiveBaseName.set('iButler')     // set the base name
    archiveVersion.set('')             // remove version number
    archiveClassifier.set('')          // remove '-plain'
}
